---
# tasks file for db02-slave
  - name: Updating remote system
    apt:
      update_cache: yes

  - name: Installing mysql python library
    apt:
      name:
        - python3-mysqldb
      state: present

  - name: Installing mysql
    apt:
      name:
        - mysql-server
      state: present

  - name: Reloading mysql
    service:
      name: mysql
      state: restarted
      enabled: true

  - name: Setuping user
    mysql_user:
      name: wordpress
      password: "wordpress"  
      login_user: wordpress  
      login_password: "wordpress"  
      check_implicit_admin: yes  
      priv: "*.*:ALL,GRANT" 

  - name: Create a new database
    mysql_db:
      name: wordpress
      state: present
      login_user: wordpress
      login_password: "wordpress"

  - name: Setuping mysql slave config
    template:
      src: templates/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf

  - name: Configuring replication on the slave
    mysql_replication:
      mode: changeprimary
      primary_host: 192.168.101.12
      primary_user: wordpress
      primary_password: "wordpress"
      primary_log_file: mysql-bin.000001
      primary_log_pos: 157

  - name: Reloading mysql
    service:
      name: mysql
      state: restarted
      enabled: true

  - name: Reseting replica
    mysql_replication: 
      mode: resetreplica

  - name: Starting replica
    mysql_replication:
      mode: startreplica


