---
# tasks file for db01-master
  - name: Updating remote system
    apt:
      update_cache: yes

  - name: Installing mysql python library
    apt:
      name:
        - python3-mysqldb
      state: present

  - name: Installing mysql
    apt:
      name:
        - mysql-server
      state: present

  - name: Reloading mysql
    service:
      name: mysql
      state: restarted
      enabled: true

  - name: Setuping user
    mysql_user:
      name: wordpress
      password: "wordpress"  
      login_user: wordpress  
      login_password: "wordpress"  
      check_implicit_admin: yes  
      priv: "*.*:ALL,GRANT" 
      host: "%"

  - name: Creating a new database  
    mysql_db: 
      name: wordpress 
      state: present 
      login_user: wordpress 
      login_password: "wordpress"

  - name: Setuping mysql master config
    template:
      src: templates/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf

  - name: Reloading mysql
    service:
      name: mysql
      state: restarted
      enabled: true

